### ISSUE TITLE
Stuck on converting world

### ISSUE THREAD

**Issue by TumbleBee6** [LudoCrypt/Backrooms-1.7.10#1]
MultiMC version: 0.6.12-1530

Minecraft folder is:
C:/Users/TumbleBee6/Documents/MultiMC/instances/legacy_fabric_1.7.10/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_281, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/TumbleBee6/Documents/MultiMC/instances/legacy_fabric_1.7.10/natives

Libraries:
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/mojang/netty/1.7.7/netty-1.7.7.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/intermediary/1.7.10/intermediary-1.7.10.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/fabric-loader-1.8.9/0.11.1+build.202102220648/fabric-loader-1.8.9-0.11.1+build.202102220648.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-32.jar
  C:/Users/TumbleBee6/Documents/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Mods:
  [✔️] fastutil-8.5.4
  [✔️] the-backrooms-1.0.0

Params:
  --username  --version MultiMC5 --gameDir C:/Users/TumbleBee6/Documents/MultiMC/instances/legacy_fabric_1.7.10/.minecraft --assetsDir C:/Users/TumbleBee6/Documents/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 20468

Using onesix launcher.

[15:04:39] [main/INFO]: Loading for game Minecraft 1.7.10
[15:04:40] [main/INFO]: [FabricLoader] Loading 6 mods: mm@2.2, minecraft@1.7.10, java@8, it_unimi_dsi_fastutil@8.5.4, fabricloader@0.11.1+build.202102220648, backrooms@1.0.0
[15:04:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/TumbleBee6/Documents/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[15:04:40] [main/INFO]: Setting user: BigCGamer
[15:04:40] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
Completely ignored arguments: [--versionType, Fabric]
[15:04:40] [Client thread/INFO]: Definitely not up to no good
[15:04:40] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:04:41] [Client thread/INFO]: Reloading ResourceManager: Default

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.
[15:04:41] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas

[15:04:42] [Sound Library Loader/INFO]: Sound engine started
[15:04:42] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[15:04:49] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[15:04:49] [Server thread/INFO]: Generating keypair
[15:04:49] [Server thread/INFO]: Converting map!
[15:04:49] [Server thread/INFO]: Scanning folders...
[15:04:49] [Server thread/INFO]: Total conversion count is 0
[15:04:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/doubles/DoubleList
	at net.ludocrypt.backrooms.world.biome.MultiNoiseBiomeSource.<clinit>(MultiNoiseBiomeSource.java:30) ~[the-backrooms-1.0.0.jar:?]
	at net.minecraft.class_630.handler$zzg000$BACKROOMS_saveBackrooms(class_630.java:541) ~[intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.class_630.method_2022(class_630.java:133) ~[intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_6439(MinecraftServer.java:134) ~[intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.class_1315.method_6441(class_1315.java:54) ~[intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.class_1315.method_6506(class_1315.java:99) ~[intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:339) [intermediary-minecraft-1.7.10-client.jar:?]
	at net.minecraft.class_2553.run(class_2553.java:628) [intermediary-minecraft-1.7.10-client.jar:?]
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.doubles.DoubleList
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:169) ~[fabric-loader-1.8.9-0.11.1+build.202102220648.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 8 more
[15:04:49] [Server thread/ERROR]: This crash report has been saved to: C:\Users\TumbleBee6\Documents\MultiMC\instances\legacy_fabric_1.7.10\.minecraft\crash-reports\crash-2021-08-18_15.04.49-server.txt
[15:04:49] [Server thread/INFO]: Stopping server
[15:04:49] [Server thread/INFO]: Saving players
Process was killed by user.
Clipboard copy at: 18 Aug 2021 15:05:57 -0700

**Comment by LudoCrypt** [comment]
fixed in latest
